NAME := board_ac692x

$(NAME)_TYPE    := kernel
MODULE          := AC692X
HOST_CHIP       := ac692x
HOST_ARCH       := pi32
HOST_MCU_FAMILY := ac69xx

$(NAME)_SOURCES := board_init.c

GLOBAL_INCLUDES += include/

CONFIG_SYSINFO_OS_VERSION       := $(call get-os-version)
CONFIG_SYSINFO_PRODUCT_MODEL    := ALI_OS_CKHOBBIT
CONFIG_SYSINFO_DEVICE_NAME      := CKHOBBIT

GLOBAL_CFLAGS   += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
GLOBAL_CFLAGS   += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_LDFLAGS  +=

EXTRA_TARGET_MAKEFILES +=  $(SOURCE_ROOT)/platform/mcu/$(HOST_MCU_FAMILY)/gen_app_bin.mk
